api_platform:
    title: Instamed Rpps Database
    description: This is a database of medical infos
    version: 4.0.0
    show_webby: false
    enable_entrypoint: true
    enable_docs: true
    enable_re_doc: true
    allow_plain_identifiers: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'

    collection:
        order_parameter_name: '_order'
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: _per_page
            maximum_items_per_page: 100
    doctrine:
        enabled: true
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        jsonapi:
            mime_types: [ 'application/vnd.api+json' ]
        html:
            mime_types: ['text/html']
        csv:
            mime_types: ['text/csv']

    patch_formats:
        json: ['application/merge-patch+json']

    error_formats:
        jsonld:
            mime_types: ['application/ld+json']
